from datetime import date as date_
from datetime import datetime
from datetime import time as time_

from sqlalchemy import DateTime, ForeignKey, Integer, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class Exam(Base):
    """A scheduled, school-wide/seated exam for one class+subject - the playbook's
    "exam scheduling, seating allocation, invigilation management," NOT Person B's
    online quizzes/assessments (checked backend/app/models/ before writing this -
    no exams/quizzes concept exists anywhere yet, no naming collision)."""

    __tablename__ = "exams"

    id: Mapped[int] = mapped_column(primary_key=True)
    school_id: Mapped[int] = mapped_column(ForeignKey("schools.id"), nullable=False)
    subject_id: Mapped[int] = mapped_column(ForeignKey("subjects.id"), nullable=False)
    class_id: Mapped[int] = mapped_column(ForeignKey("classes.id"), nullable=False)
    academic_year: Mapped[str] = mapped_column(String(20), nullable=False)
    exam_type: Mapped[str | None] = mapped_column(String(30))
    """Free text, e.g. "class_test"/"unit_test"/"mid_term"/"end_term" - not an
    enum, same spirit as FeeSchedule.fee_type/Intervention.action_taken elsewhere
    in this codebase. Nullable for rows predating this field."""
    exam_date: Mapped[date_] = mapped_column(nullable=False)
    start_time: Mapped[time_] = mapped_column(nullable=False)
    end_time: Mapped[time_] = mapped_column(nullable=False)
    total_marks: Mapped[int | None] = mapped_column(Integer)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    school: Mapped["School"] = relationship()
    subject: Mapped["Subject"] = relationship()
    school_class: Mapped["SchoolClass"] = relationship()


class ExamRoomAssignment(Base):
    """Which rooms are used for an exam and how many seats each contributes - reuses
    Room from models/timetable.py (per this session's own instruction) rather than
    duplicating a second room concept."""

    __tablename__ = "exam_room_assignments"
    __table_args__ = (UniqueConstraint("exam_id", "room_id", name="uq_exam_room"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    exam_id: Mapped[int] = mapped_column(ForeignKey("exams.id"), nullable=False)
    room_id: Mapped[int] = mapped_column(ForeignKey("rooms.id"), nullable=False)
    capacity: Mapped[int] = mapped_column(Integer, nullable=False)
    """Seats allocated to this room for this exam - may be <= Room.capacity (e.g.
    spaced-out exam seating); never validated against it, that's the caller's call."""

    exam: Mapped["Exam"] = relationship()
    room: Mapped["Room"] = relationship()


class SeatingAssignment(Base):
    """One student's assigned seat for one exam - generated by
    services/exam_scheduler.py's seating fill, persisted by
    POST /admin/exams/{id}/schedules."""

    __tablename__ = "seating_assignments"
    __table_args__ = (
        UniqueConstraint("exam_id", "student_id", name="uq_seating_exam_student"),
        UniqueConstraint("exam_id", "room_id", "seat_no", name="uq_seating_exam_room_seat"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    exam_id: Mapped[int] = mapped_column(ForeignKey("exams.id"), nullable=False)
    student_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    room_id: Mapped[int] = mapped_column(ForeignKey("rooms.id"), nullable=False)
    seat_no: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    exam: Mapped["Exam"] = relationship()
    student: Mapped["User"] = relationship()
    room: Mapped["Room"] = relationship()


class InvigilationAssignment(Base):
    """One teacher's invigilation duty for one exam room - mirrors Substitution's
    status semantics (models/staffing.py), simplified to the two states this
    session's endpoint list actually supports (no confirm/decline endpoint was
    requested, so `status` stays "assigned" for everything this session creates -
    see services/exam_scheduler.py and routers/exams.py's module docstrings for why
    this isn't registered as a 9th alert_aggregator source)."""

    __tablename__ = "invigilation_assignments"
    __table_args__ = (UniqueConstraint("exam_id", "room_id", name="uq_invigilation_exam_room"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    exam_id: Mapped[int] = mapped_column(ForeignKey("exams.id"), nullable=False)
    room_id: Mapped[int] = mapped_column(ForeignKey("rooms.id"), nullable=False)
    teacher_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    status: Mapped[str] = mapped_column(String(10), nullable=False, server_default="assigned")
    """One of: assigned, confirmed."""
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    exam: Mapped["Exam"] = relationship()
    room: Mapped["Room"] = relationship()
    teacher: Mapped["User"] = relationship()
