"""add alert dismissals table

Revision ID: 075063b5193a
Revises: 29e4855d324f
Create Date: 2026-08-12 19:01:46.380664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075063b5193a'
down_revision: Union[str, None] = '29e4855d324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=100), nullable=False),
    sa.Column('dismissed_by', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_dismissals')
    # ### end Alembic commands ###
