"""add periods_per_week and lab_required to subjects

Revision ID: 08d24eabf336
Revises: 99465d8bb6f0
Create Date: 2026-08-15 16:59:15.856854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d24eabf336'
down_revision: Union[str, None] = '99465d8bb6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('periods_per_week', sa.Integer(), server_default='3', nullable=False))
    op.add_column('subjects', sa.Column('lab_required', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'lab_required')
    op.drop_column('subjects', 'periods_per_week')
    # ### end Alembic commands ###
