"""scope resources and kb_chunks by grade_level not class_id

Revision ID: 35f1fab38e0b
Revises: a78ec6eac8a4
Create Date: 2026-08-17 00:47:56.335077

HAND-WRITTEN, not the autogenerated output. Autogenerate proposed three things that
would each have been wrong here:

  1. `add_column(grade_level, nullable=False)` then `drop_column(class_id)` - which
     fails outright on a table that already has rows (18 chunks, 3 resources), and
     would throw away the class->grade mapping that is the only way to derive the new
     value. The add/backfill/alter-NOT-NULL/drop sequence below preserves it.
  2. `drop_index('ix_kb_chunks_embedding_hnsw')` - autogenerate has no model-level
     awareness of pgvector index types, so it sees the HNSW index as an orphan and
     removes it. Dropping it would silently turn every retrieval into a sequential
     scan. It is deliberately left alone here.
  3. Dropping the class_id FK on kb_chunks WITHOUT adding school_id - grade_level is
     not unique across schools (grade 1 exists everywhere), so chunks scoped only by
     grade would be readable cross-tenant. school_id is added and backfilled here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f1fab38e0b'
down_revision: Union[str, None] = 'a78ec6eac8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- resources: class_id -> grade_level ------------------------------------
    op.add_column("resources", sa.Column("grade_level", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE resources SET grade_level = c.grade_level "
        "FROM classes c WHERE c.id = resources.class_id"
    )
    # A class with a NULL grade_level would leave the resource unusable and block the
    # NOT NULL below. Park those at grade 0 rather than failing the migration - an
    # explicitly invalid grade nothing will ever match is safer than a silent guess.
    op.execute("UPDATE resources SET grade_level = 0 WHERE grade_level IS NULL")
    op.alter_column("resources", "grade_level", nullable=False)

    op.drop_index("ix_resources_class_id", table_name="resources")
    op.drop_index("ix_resources_school_id", table_name="resources")
    op.drop_constraint("resources_class_id_fkey", "resources", type_="foreignkey")
    op.drop_column("resources", "class_id")
    op.create_index("ix_resources_school_grade", "resources", ["school_id", "grade_level"], unique=False)

    # --- kb_chunks: class_id -> (school_id, grade_level) -----------------------
    op.add_column("kb_chunks", sa.Column("school_id", sa.Integer(), nullable=True))
    op.add_column("kb_chunks", sa.Column("grade_level", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE kb_chunks SET grade_level = c.grade_level, school_id = c.school_id "
        "FROM classes c WHERE c.id = kb_chunks.class_id"
    )
    op.execute("UPDATE kb_chunks SET grade_level = 0 WHERE grade_level IS NULL")
    # school_id has no safe default - a chunk we cannot attribute to a school must not
    # become searchable by everyone. Delete rather than guess; re-ingestion rebuilds it
    # from the resource, which is cheap and idempotent.
    op.execute("DELETE FROM kb_chunks WHERE school_id IS NULL")
    op.alter_column("kb_chunks", "school_id", nullable=False)
    op.alter_column("kb_chunks", "grade_level", nullable=False)

    op.drop_index("ix_kb_chunks_class_id", table_name="kb_chunks")
    op.drop_constraint("kb_chunks_class_id_fkey", "kb_chunks", type_="foreignkey")
    op.drop_column("kb_chunks", "class_id")
    op.create_foreign_key("kb_chunks_school_id_fkey", "kb_chunks", "schools", ["school_id"], ["id"])
    op.create_index("ix_kb_chunks_school_grade", "kb_chunks", ["school_id", "grade_level"], unique=False)
    # ix_kb_chunks_embedding_hnsw is deliberately NOT touched - see the module docstring.


def downgrade() -> None:
    # Reverses the shape. The class_id values themselves are NOT recoverable (a grade
    # maps to many sections), so restored rows get the lowest-id class at that grade -
    # structurally valid, but re-ingest afterwards if you care about exact placement.
    op.add_column("kb_chunks", sa.Column("class_id", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE kb_chunks SET class_id = ("
        "  SELECT MIN(c.id) FROM classes c "
        "  WHERE c.school_id = kb_chunks.school_id AND c.grade_level = kb_chunks.grade_level)"
    )
    op.execute("DELETE FROM kb_chunks WHERE class_id IS NULL")
    op.alter_column("kb_chunks", "class_id", nullable=False)
    op.drop_index("ix_kb_chunks_school_grade", table_name="kb_chunks")
    op.drop_constraint("kb_chunks_school_id_fkey", "kb_chunks", type_="foreignkey")
    op.drop_column("kb_chunks", "grade_level")
    op.drop_column("kb_chunks", "school_id")
    op.create_foreign_key("kb_chunks_class_id_fkey", "kb_chunks", "classes", ["class_id"], ["id"])
    op.create_index("ix_kb_chunks_class_id", "kb_chunks", ["class_id"], unique=False)

    op.add_column("resources", sa.Column("class_id", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE resources SET class_id = ("
        "  SELECT MIN(c.id) FROM classes c "
        "  WHERE c.school_id = resources.school_id AND c.grade_level = resources.grade_level)"
    )
    op.execute("DELETE FROM resources WHERE class_id IS NULL")
    op.alter_column("resources", "class_id", nullable=False)
    op.drop_index("ix_resources_school_grade", table_name="resources")
    op.drop_column("resources", "grade_level")
    op.create_foreign_key("resources_class_id_fkey", "resources", "classes", ["class_id"], ["id"])
    op.create_index("ix_resources_class_id", "resources", ["class_id"], unique=False)
    op.create_index("ix_resources_school_id", "resources", ["school_id"], unique=False)
