"""add teacher_profiles table and grade_level/section on classes

Revision ID: 585dc64d1dee
Revises: 59e44568bbea
Create Date: 2026-08-15 11:20:51.378779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585dc64d1dee'
down_revision: Union[str, None] = '59e44568bbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('max_periods_per_week', sa.Integer(), server_default='30', nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.add_column('classes', sa.Column('grade_level', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('section', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###

    # Data backfill (not autogenerated): existing seeded rows only ever look like
    # "Class 8A" / "Class 8B" - trailing digits = grade_level, trailing letters =
    # section. Rows that don't match this shape are left NULL rather than guessed
    # at; real generation runs that need grade_level/section will simply not
    # resolve those rows, same honesty as any other "no matching data" case.
    op.execute(
        r"""
        UPDATE classes
        SET grade_level = (regexp_match(name, '(\d+)\s*([A-Za-z]*)\s*$'))[1]::integer,
            section = NULLIF((regexp_match(name, '(\d+)\s*([A-Za-z]*)\s*$'))[2], '')
        WHERE name ~ '\d+\s*[A-Za-z]*\s*$'
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'section')
    op.drop_column('classes', 'grade_level')
    op.drop_table('teacher_profiles')
    # ### end Alembic commands ###
