"""add school_id to documents for tenant scoping

Revision ID: 5cfd9501f709
Revises: 819485e5a52e
Create Date: 2026-08-15 13:08:55.127623

Fixes a reliability-audit-confirmed cross-tenant leak: GET /admin/ocr/documents
had zero tenant scoping (any admin/principal saw every school's documents).

NULLABLE, NO BACKFILL ATTEMPTED - deliberately, not an oversight
------------------------------------------------------------------
Checked every existing Document row before writing this migration: all 13 were
uploaded by a shared test account whose own User.school_id is itself NULL (see
services/auth.py's _get_or_create_user, which never sets school_id) - there is no
honest value to backfill from. Making the column NOT NULL with a fabricated
default (e.g. the demo school's id) would misattribute pre-existing rows to a
school that never actually uploaded them. Left NULL instead: every school_id-
scoped endpoint (list/detail/correct/reextract, see routers/documents.py) simply
never matches a NULL school_id, so these become permanently invisible through
the API - a legacy row nobody can query into the wrong tenant, not silently
exposed, and not force-deleted either (a human can still inspect/backfill them
directly if their real school is ever identified some other way). Every NEW
upload always sets a real school_id via a required form field.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cfd9501f709'
down_revision: Union[str, None] = '819485e5a52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'school_id')
    # ### end Alembic commands ###
