"""add is_active to schools classes subjects rooms users

Revision ID: 819485e5a52e
Revises: 585dc64d1dee
Create Date: 2026-08-15 12:41:25.740533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819485e5a52e'
down_revision: Union[str, None] = '585dc64d1dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('subjects', 'is_active')
    op.drop_column('schools', 'is_active')
    op.drop_column('rooms', 'is_active')
    op.drop_column('classes', 'is_active')
    # ### end Alembic commands ###
