"""add guardian_name and guardian_phone to admission_applications

Revision ID: 89691c6e955f
Revises: b1597b06c11d
Create Date: 2026-08-16 16:36:09.720031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89691c6e955f'
down_revision: Union[str, None] = 'b1597b06c11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_applications', sa.Column('guardian_name', sa.String(length=255), nullable=True))
    op.add_column('admission_applications', sa.Column('guardian_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission_applications', 'guardian_phone')
    op.drop_column('admission_applications', 'guardian_name')
    # ### end Alembic commands ###
