"""add grade_label to classes

Revision ID: 99465d8bb6f0
Revises: 5cfd9501f709
Create Date: 2026-08-15 14:07:21.996895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99465d8bb6f0'
down_revision: Union[str, None] = '5cfd9501f709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('grade_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'grade_label')
    # ### end Alembic commands ###
