"""add resources, kb_chunks, chatbot_logs for RAG

Revision ID: a78ec6eac8a4
Revises: e0bdb361c87c
Create Date: 2026-08-16 23:47:20.719377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Hand-added: autogenerate emitted `pgvector.sqlalchemy.vector.VECTOR(...)` below but
# did NOT emit this import, so the generated file raised NameError on apply. The
# earlier vector migration (fd046d263fe1_add_attendance_cv_tables) carries the same
# import for the same reason.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a78ec6eac8a4'
down_revision: Union[str, None] = 'e0bdb361c87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_type', sa.String(length=20), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('kb_chunks_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbot_logs_class_id', 'chatbot_logs', ['class_id'], unique=False)
    op.create_index('ix_chatbot_logs_created_at', 'chatbot_logs', ['created_at'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'chunk_index', name='uq_kb_chunk_source_index')
    )
    op.create_index('ix_kb_chunks_class_id', 'kb_chunks', ['class_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resources_class_id', 'resources', ['class_id'], unique=False)
    op.create_index('ix_resources_school_id', 'resources', ['school_id'], unique=False)
    # ### end Alembic commands ###

    # --- HAND-WRITTEN: HNSW index on kb_chunks.embedding -----------------------------
    # Alembic autogenerate cannot emit pgvector index types (it has no awareness of
    # `USING hnsw` or the vector opclasses), so this is raw DDL. It is also the FIRST
    # ANN index in this schema - face_embeddings.embedding has none and brute-force
    # scans every row on each recognition.
    #
    # vector_cosine_ops matches the `<=>` operator the retrieval query uses. Using a
    # different opclass here (l2_ops / ip_ops) would not error - the planner would
    # simply ignore the index and silently fall back to a sequential scan, which looks
    # like "retrieval works, just slowly" rather than a misconfiguration.
    #
    # m=16, ef_construction=64 are pgvector's own defaults, stated explicitly so the
    # values are visible and tunable rather than implicit.
    op.execute(
        "CREATE INDEX ix_kb_chunks_embedding_hnsw ON kb_chunks "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    # Hand-added, must precede the drop_table below (dropping the table would take the
    # index with it, but being explicit keeps the downgrade readable and order-safe).
    op.execute("DROP INDEX IF EXISTS ix_kb_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resources_school_id', table_name='resources')
    op.drop_index('ix_resources_class_id', table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_kb_chunks_class_id', table_name='kb_chunks')
    op.drop_table('kb_chunks')
    op.drop_index('ix_chatbot_logs_created_at', table_name='chatbot_logs')
    op.drop_index('ix_chatbot_logs_class_id', table_name='chatbot_logs')
    op.drop_table('chatbot_logs')
    # ### end Alembic commands ###
