"""add home_room_id to classes

Revision ID: b1597b06c11d
Revises: 08d24eabf336
Create Date: 2026-08-15 17:37:45.760293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1597b06c11d'
down_revision: Union[str, None] = '08d24eabf336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('home_room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'rooms', ['home_room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'home_room_id')
    # ### end Alembic commands ###
