"""add audit log entries table

Revision ID: b3e007046009
Revises: 52c1d9f5ca66
Create Date: 2026-08-12 20:07:33.214504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3e007046009'
down_revision: Union[str, None] = '52c1d9f5ca66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entries_actor_id', 'audit_log_entries', ['actor_id'], unique=False)
    op.create_index('ix_audit_log_entries_entity_type_entity_id', 'audit_log_entries', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_entries_entity_type_entity_id', table_name='audit_log_entries')
    op.drop_index('ix_audit_log_entries_actor_id', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
