"""add decision_comment to leave_requests

Revision ID: e0bdb361c87c
Revises: f2e82d59146a
Create Date: 2026-08-16 22:56:59.442749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bdb361c87c'
down_revision: Union[str, None] = 'f2e82d59146a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('decision_comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'decision_comment')
    # ### end Alembic commands ###
