"""add notifications table

Revision ID: f2e82d59146a
Revises: f4d0c4b0a6c9
Create Date: 2026-08-16 21:34:36.903848

Hand-corrected after autogenerate: the generated output also created a standalone
`ix_notifications_user_id`, which is redundant - the (user_id, read_at) composite
below already indexes user_id as its leading column, so Postgres uses it for
user_id-only lookups too. Keeping both would have cost an extra index write on
every notification insert for no read benefit. The model was changed to match
(app/models/notification.py: no index=True on user_id).

DOWNGRADE IS UNVERIFIED - the SQL is correct but was never executed
--------------------------------------------------------------------
`upgrade()` has been run against the real database and `alembic check` is clean.
`downgrade()` has NOT been: DROP TABLE notifications needs an AccessExclusiveLock
on `users` too (to tear down the FK), and every attempt was blocked by a
long-lived `idle in transaction` session elsewhere on this shared Supabase
instance holding an AccessShareLock on `users`. The generated SQL was verified by
rendering it offline (`alembic downgrade <rev>:<prev> --sql`) - DROP INDEX, DROP
TABLE, UPDATE alembic_version - but if you are the first to actually run it, do it
against a database with no other active clients and expect to wait on that lock.
Note also that a pending AccessExclusiveLock request queues every subsequent query
on `users` behind it, so a blocked downgrade will stall the whole app until it
times out - don't leave one waiting.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e82d59146a'
down_revision: Union[str, None] = 'f4d0c4b0a6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), server_default='normal', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Serves the unread-count query (user_id + read_at IS NULL) that every client
    # polls and the SSE stream re-runs per tick, and covers plain per-user inbox
    # reads via the leading column.
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
