"""add exam_type to exams

Revision ID: f4d0c4b0a6c9
Revises: 0837d66986d0
Create Date: 2026-08-16 19:26:30.648223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d0c4b0a6c9'
down_revision: Union[str, None] = '0837d66986d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('exam_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'exam_type')
    # ### end Alembic commands ###
