import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Armchair,
  Bot,
  BookOpen,
  BookOpenCheck,
  CalendarClock,
  Calendar as CalendarIcon,
  ClipboardList,
  Compass,
  FileCheck2,
  FileText,
  FolderKanban,
  GraduationCap,
  HelpCircle,
  LayoutGrid,
  Megaphone,
  Library,
  MessageSquare,
  MessagesSquare,
  School,
  ScanText,
  ScanFace,
  TrendingUp,
  Users,
  Wallet,
  User as UserIcon,
} from "lucide-react";
import type { Role } from "@/store/authStore";

/** A live count rendered on a nav item. The Layout resolves the key to a hook -
 * navConfig stays a plain data module with no data-fetching in it.
 *
 * Exists because the fee payment queue became a TAB rather than its own page, and an
 * inbox that parents are waiting on cannot only be visible once you're already on the
 * right screen. */
export type NavBadge = "pending-fee-payment-requests";

export interface NavItem {
  label: string;
  path: string;
  icon: LucideIcon;
  end?: boolean;
  badge?: NavBadge;
}

export const NAV_ITEMS: Record<Role, NavItem[]> = {
  admin: [
    { label: "Command Center", path: "/admin", icon: LayoutGrid, end: true },
    { label: "Announcements", path: "/admin/announcements", icon: Megaphone },
    { label: "Fees", path: "/admin/fees", icon: Wallet, badge: "pending-fee-payment-requests" },
    { label: "Attendance", path: "/admin/attendance", icon: ScanFace },
    { label: "Timetable", path: "/admin/timetable", icon: CalendarClock },
    { label: "Early-Warning", path: "/admin/risk", icon: AlertTriangle },
    { label: "Staffing", path: "/admin/staffing", icon: Users },
    { label: "Syllabus", path: "/admin/syllabus", icon: BookOpenCheck },
    { label: "Approvals", path: "/admin/approvals", icon: FileCheck2 },
    { label: "Document OCR", path: "/admin/ocr", icon: ScanText },
    { label: "Admissions", path: "/admin/admissions", icon: ClipboardList },
    { label: "Exams", path: "/admin/exams", icon: Armchair },
    { label: "School Management", path: "/admin/school-management", icon: School },
    { label: "Classroom", path: "/admin/classroom", icon: BookOpen },
    { label: "Resources", path: "/admin/resources", icon: FolderKanban },
    { label: "Assignments", path: "/admin/assignments", icon: ClipboardList },
    { label: "Quizzes", path: "/admin/quizzes", icon: HelpCircle },
    { label: "Gradebook", path: "/admin/gradebook", icon: GraduationCap },
    { label: "Report Cards", path: "/admin/report-cards", icon: FileText },
    { label: "Digital Library", path: "/admin/library", icon: Library },
    { label: "Homework Calendar", path: "/admin/calendar", icon: CalendarIcon },
    { label: "Student Analytics", path: "/admin/analytics", icon: TrendingUp },
    { label: "Remarks", path: "/admin/remarks", icon: MessageSquare },
    { label: "Syllabus Pace", path: "/admin/syllabus-pace", icon: Compass },
  ],
  principal: [
    { label: "Dashboard", path: "/principal", icon: LayoutGrid, end: true },
    { label: "Announcements", path: "/principal/announcements", icon: Megaphone },
    { label: "Fees", path: "/principal/fees", icon: Wallet, badge: "pending-fee-payment-requests" },
    { label: "Attendance", path: "/principal/attendance", icon: ScanFace },
    { label: "Timetable", path: "/principal/timetable", icon: CalendarClock },
    { label: "Early-Warning", path: "/principal/risk", icon: AlertTriangle },
    { label: "Staffing", path: "/principal/staffing", icon: Users },
    { label: "Syllabus", path: "/principal/syllabus", icon: BookOpenCheck },
    { label: "Approvals", path: "/principal/approvals", icon: FileCheck2 },
    { label: "Document OCR", path: "/principal/ocr", icon: ScanText },
    { label: "Admissions", path: "/principal/admissions", icon: ClipboardList },
    { label: "Exams", path: "/principal/exams", icon: Armchair },
    { label: "School Management", path: "/principal/school-management", icon: School },
    { label: "Classroom", path: "/principal/classroom", icon: BookOpen },
    { label: "Resources", path: "/principal/resources", icon: FolderKanban },
    { label: "Assignments", path: "/principal/assignments", icon: ClipboardList },
    { label: "Quizzes", path: "/principal/quizzes", icon: HelpCircle },
    { label: "Gradebook", path: "/principal/gradebook", icon: GraduationCap },
    { label: "Report Cards", path: "/principal/report-cards", icon: FileText },
    { label: "Digital Library", path: "/principal/library", icon: Library },
    { label: "Homework Calendar", path: "/principal/calendar", icon: CalendarIcon },
    { label: "Student Analytics", path: "/principal/analytics", icon: TrendingUp },
    { label: "Remarks", path: "/principal/remarks", icon: MessageSquare },
    { label: "Syllabus Pace", path: "/principal/syllabus-pace", icon: Compass },
  ],
  teacher: [
    { label: "Dashboard", path: "/teacher", icon: LayoutGrid, end: true },
    { label: "Announcements", path: "/teacher/announcements", icon: Megaphone },
    { label: "Fees", path: "/teacher/fees", icon: Wallet },
    { label: "Attendance", path: "/teacher/attendance", icon: ScanFace },
    { label: "Timetable", path: "/teacher/timetable", icon: CalendarClock },
    { label: "Early-Warning", path: "/teacher/risk", icon: AlertTriangle },
    { label: "Doubts", path: "/teacher/doubts", icon: MessagesSquare },
    { label: "Staffing", path: "/teacher/staffing", icon: Users },
    { label: "Syllabus", path: "/teacher/syllabus", icon: BookOpenCheck },
    { label: "Exam Duties", path: "/teacher/exams", icon: Armchair },
    { label: "Assistant Bot", path: "/teacher/assistant", icon: Bot },
    { label: "Classroom", path: "/teacher/classroom", icon: BookOpen },
    { label: "Resources", path: "/teacher/resources", icon: FolderKanban },
    { label: "Assignments", path: "/teacher/assignments", icon: ClipboardList },
    { label: "Quizzes", path: "/teacher/quizzes", icon: HelpCircle },
    { label: "Gradebook", path: "/teacher/gradebook", icon: GraduationCap },
    { label: "Report Cards", path: "/teacher/report-cards", icon: FileText },
    { label: "Digital Library", path: "/teacher/library", icon: Library },
    { label: "Homework Calendar", path: "/teacher/calendar", icon: CalendarIcon },
    { label: "Student Analytics", path: "/teacher/analytics", icon: TrendingUp },
    { label: "Bulk Remarks", path: "/teacher/remarks", icon: MessageSquare },
    { label: "Syllabus Pace", path: "/teacher/syllabus-pace", icon: Compass },
  ],
  student: [
    { label: "Dashboard", path: "/student", icon: LayoutGrid, end: true },
    { label: "Announcements", path: "/student/announcements", icon: Megaphone },
    { label: "Attendance", path: "/student/attendance", icon: ScanFace },
    { label: "Doubts", path: "/student/doubts", icon: MessagesSquare },
    { label: "Classroom", path: "/student/classroom", icon: BookOpen },
    { label: "Resources", path: "/student/resources", icon: FolderKanban },
    { label: "Assignments", path: "/student/assignments", icon: ClipboardList },
    { label: "Quizzes", path: "/student/quizzes", icon: HelpCircle },
    { label: "Gradebook", path: "/student/gradebook", icon: GraduationCap },
    { label: "Report Cards", path: "/student/report-cards", icon: FileText },
    { label: "Digital Library", path: "/student/library", icon: Library },
    { label: "Homework Calendar", path: "/student/calendar", icon: CalendarIcon },
    { label: "My Analytics", path: "/student/analytics", icon: TrendingUp },
    { label: "Teacher Remarks", path: "/student/remarks", icon: MessageSquare },
    { label: "Doubt Bot", path: "/student/doubt-bot", icon: Bot },
    { label: "Timetable", path: "/student/timetable", icon: CalendarClock },
    { label: "Fees", path: "/student/fees", icon: Wallet },
    { label: "Exam Seats", path: "/student/exams", icon: Armchair },
  ],
  parent: [
    { label: "Dashboard", path: "/parent", icon: LayoutGrid, end: true },
    { label: "Announcements", path: "/parent/announcements", icon: Megaphone },
    { label: "My Child", path: "/parent/child", icon: UserIcon },
    { label: "Attendance", path: "/parent/attendance", icon: ScanFace },
    { label: "Ask", path: "/parent/bot", icon: Bot },
    { label: "Resources", path: "/parent/resources", icon: FolderKanban },
    { label: "Assignments", path: "/parent/assignments", icon: ClipboardList },
    { label: "Gradebook", path: "/parent/gradebook", icon: GraduationCap },
    { label: "Report Cards", path: "/parent/report-cards", icon: FileText },
    { label: "Homework Calendar", path: "/parent/calendar", icon: CalendarIcon },
    { label: "Child Analytics", path: "/parent/analytics", icon: TrendingUp },
    { label: "Teacher Remarks", path: "/parent/remarks", icon: MessageSquare },
    { label: "Timetable", path: "/parent/timetable", icon: CalendarClock },
    { label: "Early-Warning", path: "/parent/risk", icon: AlertTriangle },
    { label: "Fees", path: "/parent/fees", icon: Wallet },
  ],
};

export const ROLE_LABEL: Record<Role, string> = {
  admin: "Admin",
  principal: "Principal",
  teacher: "Teacher",
  student: "Student",
  parent: "Parent",
};

export { UserIcon };
